apps/pageelement/urls.py
from django.urls import path

from .views import PageEleView,ModulePageView
from .views import EleTestDataView


urlpatterns = [
    #相同参数的路径名一定不能一样。比如copy/<path:testcase_id>/与<path:testcase_id>/不能并列存在
    path('pageelecopy/<path:pageele_id>/', PageEleView.as_view(), name="page_ele_id"),  # 配置复制新增测试用例url,namespace指明命名空间，用命名空间做限定
    path('modulepagecopy/<path:modulepage_id>/', ModulePageView.as_view(), name="module_page_id"),  # 配置复制新增测试用例url,namespace指明命名空间，用命名空间做限定
    path('eletestdatacopy/<path:eletestdata_id>/', EleTestDataView.as_view(), name="ele_test_data_id"),  # 配置复制新增测试用例url,namespace指明命名空间，用命名空间做限定

]

app_name = 'pageele'

apps/testfundata/urls.py
from django.urls import path

from .views import TestSearchView



urlpatterns = [
    #相同参数的路径名一定不能一样。比如copy/<path:testcase_id>/与<path:testcase_id>/不能并列存在
    path('testsearchcopy/<path:testsearch_id>/', TestSearchView.as_view(), name="test_search_id"),  # 配置复制新增测试用例url,namespace指明命名空间，用命名空间做限定
    # path('modulepagecopy/<path:modulepage_id>/', ModulePageView.as_view(), name="module_page_id"),  # 配置复制新增测试用例url,namespace指明命名空间，用命名空间做限定
    # path('eletestdatacopy/<path:eletestdata_id>/', EleTestDataView.as_view(), name="ele_test_data_id"),  # 配置复制新增测试用例url,namespace指明命名空间，用命名空间做限定

]

app_name = 'testfundata'

webtestdata/urls.py
from django.contrib import admin
from django.urls import path,include
import xadmin

from django.views.static import serve   #导入django处理静态文件的包serve ,用于处理midia路径下的文件
from .settings import MEDIA_ROOT    #导入Settings中配置的MEDIA_ROOT

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),   #配置xadmin访问路径
    path('pageele/', include('pageelement.urls', namespace='pageele')),  # 配置测试用例url,namespace指明命名空间，用命名空间做限定
    path('testfun/', include('testfundata.urls', namespace='test_fun')),  # 配置测试用例url,namespace指明命名空间，用命名空间做限定

    # 配置上传文件的访问处理函数
    path('media/<path:path>', serve, {"document_root": MEDIA_ROOT}),
    # 配置处理引用midia路径下文件的路径,调用serve方法,需要传入参数{"document_root":MEDIA_ROOT}
]

templates/NoAddCase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>不能添加数据</title>
    账号不能添加数据。请点击<a href="http://127.0.0.1:8000/xadmin/pageelement/pageele/">数据列表</a>返回数据列表</p>
</head>
<body>

</body>
</html>

templates/addcaseError.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>不能添加数据</title>
    <p>未登录，不能添加数据，请点击<a href="http://127.0.0.1:8000/xadmin/">登录</a>登录先</p>
</head>
<body>

</body>
</html>

templates/eletestdata.html
{% extends 'pageelebase.html' %}
{% block title %}add eletestdata{% endblock %}
{% block formurl %}{% url 'pageele:ele_test_data_id' eletestdata.id %}{% endblock %}
{% block table %}
    <table cellpadding="5" cellspacing="5">
{#                <tr>#}
{#                    <td>#}
{#                        <label>测试项目:</label>#}
{#                    </td>#}
{#                    <td>#}
{#                        <select id="testproject" name="testproject">#}
{#                            {%for tp in testprojects%}#}
{#                                <option value={{forloop.counter}} {% if tp.id == eletestdata.testproject_id  %}selected="selected"{% endif %}>{{ tp.web_project}}</option>#}
{#                            {%endfor%}#}
{#                        </select>#}
{#                    </td>#}
{#                </tr>#}
{##}
{#                <tr>#}
{#                    <td>#}
{#                        <label>项目模块:</label>#}
{#                    </td>#}
{#                    <td>#}
{#                        <select id="projectmodule" name="projectmodule">#}
{#                            {%for pm in projectmodules%}#}
{#                                <option value={{forloop.counter}} {% if pm.id == eletestdata.projectmodule_id %}selected="selected"{% endif %}>{{ pm.web_module}}</option>#}
{#                            {%endfor%}#}
{#                        </select>#}
{#                    </td>#}
{#                </tr>#}
{##}
{#                <tr>#}
{#                    <td>#}
{#                        <label>模块页面:</label>#}
{#                    </td>#}
{#                    <td>#}
{#                        <select id="modulepage" name="modulepage">#}
{#                            {%for mp in modulepages%}#}
{#                                <option value={{forloop.counter}} {% if mp.id == eletestdata.modulepage_id%}selected="selected"{% endif %}>{{ mp.ele_page}}</option>#}
{#                            {%endfor%}#}
{#                        </select>#}
{#                    </td>#}
{#                </tr>#}

                <tr>
                    <td>
                        <label>页面元素:</label>
                    </td>
                    <td>
                        <select id="pageele" name="pageele">
                            {%for pe in pageeles%}
                                <option value={{forloop.counter}} {% if pe.id == eletestdata.pageele_id%}selected="selected"{% endif %}>{{ pe.modulepage }}-{{ pe.ele_name }}</option>
                            {%endfor%}
                        </select>
                    </td>
                </tr>

                <tr>
                    <td>
                        <label>元素测试数据类型:</label>
                    </td>
                    <td>
                        <select id="eletestdatatype" name="eletestdatatype">
                            {%for etdt in eletestdatatypes%}
                                <option value={{forloop.counter}} {% if etdt.id == eletestdata.eletestdatatype_id%}selected="selected"{% endif %}>{{ etdt.test_data_type }}</option>
                            {%endfor%}
                        </select>
                    </td>
                </tr>

                <tr>
                    <td>
                        <label>元素测试数据:</label>
                    </td>
                    <td>
                        <input id="test_data" name="test_data" type="text" value="{{ eletestdata.test_data }}"/>
                    </td>
                </tr>


{#                <tr>#}
{#                    <td>#}
{#                        <label>web模块:</label>#}
{#                    </td>#}
{#                    <td>#}
{#                        <input id="web_module" name="web_module" type="text" value="{{ modulepage.web_module }}"/>#}
{#                    </td>#}
{#                </tr>#}
{##}
{#                <tr>#}
{#                    <td>#}
{#                        <label>元素页面:</label>#}
{#                    </td>#}
{#                    <td>#}
{#                        <input id="ele_page" name="ele_page" type="text" value="{{ modulepage.ele_page }}"/>#}
{#                    </td>#}
{#                </tr>#}

    {#            <tr>#}
    {#                <td>#}
    {#                    <label>功能点:</label>#}
    {#                </td>#}
    {#                <td>#}
    {#                    <textarea id="requirement_function" name="requirement_function"> {{ testcase.requirement_function }}</textarea>#}
    {#                </td>#}
    {#            </tr>#}

    {#            <tr>#}
    {#                <td>#}
    {#                    <label>用例优先级:</label>#}
    {#                </td>#}
    {#                <td>#}
    {#                    <input type="radio"  name="case_priority" value="P0" {% if testcase.case_priority == 'P0' %}checked="checked"{% endif %}>冒烟用例#}
    {#                    <input type="radio" name="case_priority"   value="P1" {% if testcase.case_priority  == 'P1' %}checked="checked"{% endif %}>系统的重要功能用例#}
    {#                    <input type="radio"  name="case_priority"  value="P2" {% if testcase.case_priority == 'P2' %}checked="checked"{% endif %}>系统的一般功能用例#}
    {#                    <input type="radio" name="case_priority"   value="P3" {% if testcase.case_priority  == 'P3' %}checked="checked"{% endif %}>极低级别的用例#}
    {#                </td>#}
    {#            </tr>#}

    {#            <tr>#}
    {#                <td>#}
    {#                    <label>流程类型:</label>#}
    {#                </td>#}
    {#                <td>#}
    {#                    <input type="radio"  name="case_process_type" value="normal" {% if testcase.case_process_type == 'normal' %}checked="checked"{% endif %}>正常流#}
    {#                    <input type="radio" name="case_process_type"   value="unusual" {% if testcase.case_process_type  == 'unusual' %}checked="checked"{% endif %}>异常流#}
    {#                </td>#}
    {#            </tr>#}

{#                <tr>#}
{#                    <td>#}
{#                        <label>元素页面URL:</label>#}
{#                    </td>#}
{#                    <td>#}
{#                        <input id="ele_page_url" name="ele_page_url" type="text" value="{{ modulepage.ele_page_url }}"/>#}
{#                    </td>#}
{#                </tr>#}

{#                <tr>#}
{#                    <td>#}
{#                        <label>元素名字:</label>#}
{#                    </td>#}
{#                    <td>#}
{#                        <textarea id="ele_name" name="ele_name">{{ pageele.ele_name }}</textarea>#}
{#                    </td>#}
{#                </tr>#}
{##}
{#                <tr>#}
{#                    <td>#}
{#                        <label>元素xpath路径:</label>#}
{#                    </td>#}
{#                    <td>#}
{#                        <textarea id="ele_xpath" name="ele_xpath">{{ pageele.ele_xpath }}</textarea>#}
{#                    </td>#}
{#                </tr>#}

    {#            <tr>#}
    {#                <td>#}
    {#                    <label>测试用例预期结果:</label>#}
    {#                </td>#}
    {#                <td>#}
    {#                    <textarea id="case_expected_result" name="case_expected_result"> {{ testcase.case_expected_result }}</textarea>#}
    {#                </td>#}
    {#            </tr>#}
    {##}
    {#            <tr>#}
    {#                <td>#}
    {#                    <label>编写备注:</label>#}
    {#                </td>#}
    {#                <td>#}
    {#                    <textarea id="write_comments" name="write_comments"> {{ testcase.write_comments }}</textarea>#}
    {#                </td>#}
    {#            </tr>#}
    {#            <tr>#}
    {#                <td>#}
    {#                    <label>编写人员:</label>#}
    {#                </td>#}
    {#                <td>#}
    {#                    <input id="write_user" name="write_user"  type="text" readonly="readonly"  value="{{ testcase.write_user|default:'' }}"/>#}
    {#                </td>#}
    {#            </tr>#}
            </table>
{% endblock %}

{% block backlist %}'http://127.0.0.1:8000/xadmin/pageelement/eletestdata/'{% endblock %}

templates/modulepage.html
{% extends 'pageelebase.html' %}
{% block title %}add modulepage{% endblock %}
{% block formurl %}{% url 'pageele:module_page_id' modulepage.id %}{% endblock %}
{% block table %}
    <table cellpadding="5" cellspacing="5">
                <tr>
                    <td>
                        <label>测试项目:</label>
                    </td>
                    <td>
                        <select id="testproject" name="testproject">
                            {%for tp in testprojects%}
                                <option value={{forloop.counter}} {% if tp.id == modulepage.testproject_id  %}selected="selected"{% endif %}>{{ tp.web_project}}</option>
                            {%endfor%}
                        </select>
                    </td>
                </tr>

                <tr>
                    <td>
                        <label>项目模块:</label>
                    </td>
                    <td>
                        <select id="projectmodule" name="projectmodule">
                            {%for pm in projectmodules%}
                                <option value={{forloop.counter}} {% if pm.id == modulepage.projectmodule_id %}selected="selected"{% endif %}>{{ pm.web_module}}</option>
                            {%endfor%}
                        </select>
                    </td>
                </tr>

                <tr>
                    <td>
                        <label>元素页面:</label>
                    </td>
                    <td>
                        <input id="ele_page" name="ele_page" type="text" value="{{ modulepage.ele_page }}"/>
                    </td>
                </tr>

    {#            <tr>#}
    {#                <td>#}
    {#                    <label>功能点:</label>#}
    {#                </td>#}
    {#                <td>#}
    {#                    <textarea id="requirement_function" name="requirement_function"> {{ testcase.requirement_function }}</textarea>#}
    {#                </td>#}
    {#            </tr>#}

    {#            <tr>#}
    {#                <td>#}
    {#                    <label>用例优先级:</label>#}
    {#                </td>#}
    {#                <td>#}
    {#                    <input type="radio"  name="case_priority" value="P0" {% if testcase.case_priority == 'P0' %}checked="checked"{% endif %}>冒烟用例#}
    {#                    <input type="radio" name="case_priority"   value="P1" {% if testcase.case_priority  == 'P1' %}checked="checked"{% endif %}>系统的重要功能用例#}
    {#                    <input type="radio"  name="case_priority"  value="P2" {% if testcase.case_priority == 'P2' %}checked="checked"{% endif %}>系统的一般功能用例#}
    {#                    <input type="radio" name="case_priority"   value="P3" {% if testcase.case_priority  == 'P3' %}checked="checked"{% endif %}>极低级别的用例#}
    {#                </td>#}
    {#            </tr>#}

    {#            <tr>#}
    {#                <td>#}
    {#                    <label>流程类型:</label>#}
    {#                </td>#}
    {#                <td>#}
    {#                    <input type="radio"  name="case_process_type" value="normal" {% if testcase.case_process_type == 'normal' %}checked="checked"{% endif %}>正常流#}
    {#                    <input type="radio" name="case_process_type"   value="unusual" {% if testcase.case_process_type  == 'unusual' %}checked="checked"{% endif %}>异常流#}
    {#                </td>#}
    {#            </tr>#}

                <tr>
                    <td>
                        <label>元素页面URL:</label>
                    </td>
                    <td>
                        <input id="ele_page_url" name="ele_page_url" type="text" value="{{ modulepage.ele_page_url }}"/>
                    </td>
                </tr>

{#                <tr>#}
{#                    <td>#}
{#                        <label>元素名字:</label>#}
{#                    </td>#}
{#                    <td>#}
{#                        <textarea id="ele_name" name="ele_name">{{ pageele.ele_name }}</textarea>#}
{#                    </td>#}
{#                </tr>#}
{##}
{#                <tr>#}
{#                    <td>#}
{#                        <label>元素xpath路径:</label>#}
{#                    </td>#}
{#                    <td>#}
{#                        <textarea id="ele_xpath" name="ele_xpath">{{ pageele.ele_xpath }}</textarea>#}
{#                    </td>#}
{#                </tr>#}

    {#            <tr>#}
    {#                <td>#}
    {#                    <label>测试用例预期结果:</label>#}
    {#                </td>#}
    {#                <td>#}
    {#                    <textarea id="case_expected_result" name="case_expected_result"> {{ testcase.case_expected_result }}</textarea>#}
    {#                </td>#}
    {#            </tr>#}
    {##}
    {#            <tr>#}
    {#                <td>#}
    {#                    <label>编写备注:</label>#}
    {#                </td>#}
    {#                <td>#}
    {#                    <textarea id="write_comments" name="write_comments"> {{ testcase.write_comments }}</textarea>#}
    {#                </td>#}
    {#            </tr>#}
    {#            <tr>#}
    {#                <td>#}
    {#                    <label>编写人员:</label>#}
    {#                </td>#}
    {#                <td>#}
    {#                    <input id="write_user" name="write_user"  type="text" readonly="readonly"  value="{{ testcase.write_user|default:'' }}"/>#}
    {#                </td>#}
    {#            </tr>#}
            </table>
{% endblock %}

{% block backlist %}'http://127.0.0.1:8000/xadmin/pageelement/modulepage/'{% endblock %}

templates/pageele.html
{% extends 'pageelebase.html' %}
{% block title %}add pageele{% endblock %}
{% block formurl %}{% url 'pageele:page_ele_id' pageele.id %}{% endblock %}
{% block table %}
    <table cellpadding="5" cellspacing="5">
{#            <tr>#}
{#                <td>#}
{#                    <label>web项目:</label>#}
{#                </td>#}
{#                <td>#}
{#                    <input id="web_project" name="web_project" type="text" value="{{ pageele.web_project }}"/>#}
{#                </td>#}
{#            </tr>#}

{#            <tr>#}
{#                <td>#}
{#                    <label>web模块:</label>#}
{#                </td>#}
{#                <td>#}
{#                    <input id="web_module" name="web_module" type="text" value="{{ pageele.web_module }}"/>#}
{#                </td>#}
{#            </tr>#}

            <tr>
                <td>
                    <label>模块页面:</label>
                </td>
                <td>
                    <select id="modulepage" name="modulepage">
                        {%for mp in modulepages%}
                            <option value={{forloop.counter}} {% if mp.id == pageele.modulepage_id%}selected="selected"{% endif %}>{{ mp.testproject }}__{{ mp.projectmodule }}_{{ mp.ele_page }}</option>
                        {%endfor%}
                    </select>
                </td>
            </tr>

{#            <tr>#}
{#                <td>#}
{#                    <label>功能点:</label>#}
{#                </td>#}
{#                <td>#}
{#                    <textarea id="requirement_function" name="requirement_function"> {{ testcase.requirement_function }}</textarea>#}
{#                </td>#}
{#            </tr>#}

{#            <tr>#}
{#                <td>#}
{#                    <label>用例优先级:</label>#}
{#                </td>#}
{#                <td>#}
{#                    <input type="radio"  name="case_priority" value="P0" {% if testcase.case_priority == 'P0' %}checked="checked"{% endif %}>冒烟用例#}
{#                    <input type="radio" name="case_priority"   value="P1" {% if testcase.case_priority  == 'P1' %}checked="checked"{% endif %}>系统的重要功能用例#}
{#                    <input type="radio"  name="case_priority"  value="P2" {% if testcase.case_priority == 'P2' %}checked="checked"{% endif %}>系统的一般功能用例#}
{#                    <input type="radio" name="case_priority"   value="P3" {% if testcase.case_priority  == 'P3' %}checked="checked"{% endif %}>极低级别的用例#}
{#                </td>#}
{#            </tr>#}

{#            <tr>#}
{#                <td>#}
{#                    <label>流程类型:</label>#}
{#                </td>#}
{#                <td>#}
{#                    <input type="radio"  name="case_process_type" value="normal" {% if testcase.case_process_type == 'normal' %}checked="checked"{% endif %}>正常流#}
{#                    <input type="radio" name="case_process_type"   value="unusual" {% if testcase.case_process_type  == 'unusual' %}checked="checked"{% endif %}>异常流#}
{#                </td>#}
{#            </tr>#}

{#            <tr>#}
{#                <td>#}
{#                    <label>元素页面URL:</label>#}
{#                </td>#}
{#                <td>#}
{#                    <input id="ele_page_url" name="ele_page_url" type="text" value="{{ pageele.ele_page_url }}"/>#}
{#                </td>#}
{#            </tr>#}

            <tr>
                <td>
                    <label>元素名字:</label>
                </td>
                <td>
                    <textarea id="ele_name" name="ele_name">{{ pageele.ele_name }}</textarea>
                </td>
            </tr>

            <tr>
                <td>
                    <label>元素xpath路径:</label>
                </td>
                <td>
                    <textarea id="ele_xpath" name="ele_xpath">{{ pageele.ele_xpath }}</textarea>
                </td>
            </tr>

{#            <tr>#}
{#                <td>#}
{#                    <label>测试用例预期结果:</label>#}
{#                </td>#}
{#                <td>#}
{#                    <textarea id="case_expected_result" name="case_expected_result"> {{ testcase.case_expected_result }}</textarea>#}
{#                </td>#}
{#            </tr>#}
{##}
{#            <tr>#}
{#                <td>#}
{#                    <label>编写备注:</label>#}
{#                </td>#}
{#                <td>#}
{#                    <textarea id="write_comments" name="write_comments"> {{ testcase.write_comments }}</textarea>#}
{#                </td>#}
{#            </tr>#}
{#            <tr>#}
{#                <td>#}
{#                    <label>编写人员:</label>#}
{#                </td>#}
{#                <td>#}
{#                    <input id="write_user" name="write_user"  type="text" readonly="readonly"  value="{{ testcase.write_user|default:'' }}"/>#}
{#                </td>#}
{#            </tr>#}
        </table>

{% endblock %}

{% block backlist %}'http://127.0.0.1:8000/xadmin/pageelement/pageele/'{% endblock %}

templates/pageelebase.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>{% block title %}add pageele{% endblock %}</title>
{#    <link rel="stylesheet" href="/static/css1/selfstyle.css">#}
{#    <link rel="stylesheet" href="{% static 'css1/style1.css' %}">#}
    <link rel="stylesheet" href="{% static 'css1/style2.css' %}">
</head>
<body>
<form action={% block formurl %}"{% url 'pageele:page_ele_id' pageele.id %}"{% endblock %} method="post" class="smart-green">
	<div >
        <h1>添加数据
            <span>
                    {% if errmsg  %}
                        <div class="error-msg">{{ errmsg }}</div>
                    {% else %}
                        <div class="success-msg">{{ sumsg }}</div>
                    {% endif %}
            </span>
        </h1>
    </div>
    <div class="kongbai"></div>
    <div class="tabledata">
        {% block table %}
            <table cellpadding="5" cellspacing="5">
                <tr>
                    <td>
                        <label>web项目:</label>
                    </td>
                    <td>
                        <input id="web_project" name="web_project" type="text" value="{{ pageele.web_project }}"/>
                    </td>
                </tr>

                <tr>
                    <td>
                        <label>web模块:</label>
                    </td>
                    <td>
                        <input id="web_module" name="web_module" type="text" value="{{ pageele.web_module }}"/>
                    </td>
                </tr>

                <tr>
                    <td>
                        <label>元素页面:</label>
                    </td>
                    <td>
                        <input id="ele_page" name="ele_page" type="text" value="{{ pageele.ele_page }}"/>
                    </td>
                </tr>

    {#            <tr>#}
    {#                <td>#}
    {#                    <label>功能点:</label>#}
    {#                </td>#}
    {#                <td>#}
    {#                    <textarea id="requirement_function" name="requirement_function"> {{ testcase.requirement_function }}</textarea>#}
    {#                </td>#}
    {#            </tr>#}

    {#            <tr>#}
    {#                <td>#}
    {#                    <label>用例优先级:</label>#}
    {#                </td>#}
    {#                <td>#}
    {#                    <input type="radio"  name="case_priority" value="P0" {% if testcase.case_priority == 'P0' %}checked="checked"{% endif %}>冒烟用例#}
    {#                    <input type="radio" name="case_priority"   value="P1" {% if testcase.case_priority  == 'P1' %}checked="checked"{% endif %}>系统的重要功能用例#}
    {#                    <input type="radio"  name="case_priority"  value="P2" {% if testcase.case_priority == 'P2' %}checked="checked"{% endif %}>系统的一般功能用例#}
    {#                    <input type="radio" name="case_priority"   value="P3" {% if testcase.case_priority  == 'P3' %}checked="checked"{% endif %}>极低级别的用例#}
    {#                </td>#}
    {#            </tr>#}

    {#            <tr>#}
    {#                <td>#}
    {#                    <label>流程类型:</label>#}
    {#                </td>#}
    {#                <td>#}
    {#                    <input type="radio"  name="case_process_type" value="normal" {% if testcase.case_process_type == 'normal' %}checked="checked"{% endif %}>正常流#}
    {#                    <input type="radio" name="case_process_type"   value="unusual" {% if testcase.case_process_type  == 'unusual' %}checked="checked"{% endif %}>异常流#}
    {#                </td>#}
    {#            </tr>#}

                <tr>
                    <td>
                        <label>元素页面URL:</label>
                    </td>
                    <td>
                        <input id="ele_page_url" name="ele_page_url" type="text" value="{{ pageele.ele_page_url }}"/>
                    </td>
                </tr>

                <tr>
                    <td>
                        <label>元素名字:</label>
                    </td>
                    <td>
                        <textarea id="ele_name" name="ele_name">{{ pageele.ele_name }}</textarea>
                    </td>
                </tr>

                <tr>
                    <td>
                        <label>元素xpath路径:</label>
                    </td>
                    <td>
                        <textarea id="ele_xpath" name="ele_xpath">{{ pageele.ele_xpath }}</textarea>
                    </td>
                </tr>

    {#            <tr>#}
    {#                <td>#}
    {#                    <label>测试用例预期结果:</label>#}
    {#                </td>#}
    {#                <td>#}
    {#                    <textarea id="case_expected_result" name="case_expected_result"> {{ testcase.case_expected_result }}</textarea>#}
    {#                </td>#}
    {#            </tr>#}
    {##}
    {#            <tr>#}
    {#                <td>#}
    {#                    <label>编写备注:</label>#}
    {#                </td>#}
    {#                <td>#}
    {#                    <textarea id="write_comments" name="write_comments"> {{ testcase.write_comments }}</textarea>#}
    {#                </td>#}
    {#            </tr>#}
    {#            <tr>#}
    {#                <td>#}
    {#                    <label>编写人员:</label>#}
    {#                </td>#}
    {#                <td>#}
    {#                    <input id="write_user" name="write_user"  type="text" readonly="readonly"  value="{{ testcase.write_user|default:'' }}"/>#}
    {#                </td>#}
    {#            </tr>#}
            </table>
        {% endblock %}
        <br/>
	</div>
    <div class="kongbai">
    </div>

    <div class="box2">
        <div class="box2button">
            <input type="submit" class="button"  value="新增加一条数据"/>
        </div>
        <div class="box2a">
            <a href={% block backlist %}'http://127.0.0.1:8000/xadmin/pageelement/pageele/'{% endblock %}>返回数据列表页</a>
        </div>
    </div>

    {% csrf_token %} <!--保证form表提交，是一种安全机制-->
</form>


{#{% block custom_js %}  <!--此处是处理"我要学习"表单的js-->#}
{#<script>#}
{#    $(function(){#}
{#        $('#jsStayBtn').on('click', function(){   <!--用户店家按钮操作函数-->#}
{#            $.ajax({#}
{#                cache: false,#}
{#                type: "POST",#}
{#                url:"{% url "testcase:add_ask" %}",#}
{#                data:$('#jsStayForm').serialize(),#}
{#                async: true,#}
{#                success: function(data) {#}
{#                    if(data.status == 'success'){ <!--如果提交成功，则弹框提示提交成功-->#}
                        {#$('#jsStayForm')[0].reset();#}
{#                        alert("提交成功")#}
{#                    }else if(data.status == 'fail'){<!--如果提交失败，则返回错误信息-->#}
                        {#$('#jsCompanyTips').html(data.msg)#}
{#                        alert("提交失败")#}
{#                    }#}
{#                },#}
{#            });#}
{#        });#}
{#    })#}
{#</script>#}
{#{% endblock %}   <!--此处可以重写js-->#}
</body>
</html>